[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyBt9MjLrF8zal8VcrJDGR8YppUGgBfEmz0"
  VITE_FIREBASE_AUTH_DOMAIN = "content-coach-a4d5f.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "content-coach-a4d5f"
  VITE_FIREBASE_STORAGE_BUCKET = "content-coach-a4d5f.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "834918314341"
  VITE_FIREBASE_APP_ID = "1:834918314341:web:beed9d88c3dcfb612a318c"
  VITE_FIREBASE_MEASUREMENT_ID = "G-GB23B7C14Y"